// <auto-generated />
using IUS_OKO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IUS_OKO.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250610042255_IUS_OKO1")]
    partial class IUS_OKO1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IUS_OKO.ParameterOKO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ParameterData")
                        .HasColumnType("boolean");

                    b.Property<string>("ParameterName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ParameterOKO");
                });
#pragma warning restore 612, 618
        }
    }
}
